# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Start mackerel
      run: ./scripts/start.sh
      env:
        MACKEREL_API_KEY: ${{ secrets.MACKEREL_API_KEY }}
  
    - name: Build NodeJS
      run: |
        git clone https://github.com/nodejs/node
        cd node
        ./configure
        make -j2


    - name: Retire
      run: ./scripts/retire.sh
  
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
